# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/game_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(600, 500))
        MainWindow.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_barWidget = QtWidgets.QWidget(self.centralwidget)
        self.title_barWidget.setMinimumSize(QtCore.QSize(0, 45))
        self.title_barWidget.setMaximumSize(QtCore.QSize(16777215, 45))
        self.title_barWidget.setStyleSheet("background-color: rgb(43, 43, 43);")
        self.title_barWidget.setObjectName("title_barWidget")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.title_barWidget)
        self.horizontalLayout_24.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.frame_icon = QtWidgets.QFrame(self.title_barWidget)
        self.frame_icon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_icon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_icon.setObjectName("frame_icon")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frame_icon)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setSpacing(0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_8 = QtWidgets.QLabel(self.frame_icon)
        self.label_8.setMaximumSize(QtCore.QSize(25, 30))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("gui\\../icons/app_icon.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_29.addWidget(self.label_8, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_24.addWidget(self.frame_icon, 0, QtCore.Qt.AlignLeft)
        self.frame_title = QtWidgets.QFrame(self.title_barWidget)
        self.frame_title.setStyleSheet("color: rgb(255, 255, 255);")
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.frame_title)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_9 = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_31.addWidget(self.label_9)
        self.horizontalLayout_24.addWidget(self.frame_title)
        self.frame_functional_butons = QtWidgets.QFrame(self.title_barWidget)
        self.frame_functional_butons.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_functional_butons.setStyleSheet("")
        self.frame_functional_butons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_functional_butons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_functional_butons.setObjectName("frame_functional_butons")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_functional_butons)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.frame_24 = QtWidgets.QFrame(self.frame_functional_butons)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.btn_minimize_window = QtWidgets.QPushButton(self.frame_24)
        self.btn_minimize_window.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_minimize_window.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_minimize_window.setStyleSheet("border-radius: 10px;\n"
"\n"
"background-color: rgb(81, 81, 81);")
        self.btn_minimize_window.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("gui\\../icons/minimize_window_black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimize_window.setIcon(icon)
        self.btn_minimize_window.setObjectName("btn_minimize_window")
        self.horizontalLayout_28.addWidget(self.btn_minimize_window)
        self.horizontalLayout_25.addWidget(self.frame_24)
        self.frame_23 = QtWidgets.QFrame(self.frame_functional_butons)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.btn_maximize_restore_window = QtWidgets.QPushButton(self.frame_23)
        self.btn_maximize_restore_window.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_maximize_restore_window.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_maximize_restore_window.setStyleSheet("border-radius: 10px;\n"
"\n"
"background-color: rgb(81, 81, 81);")
        self.btn_maximize_restore_window.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("gui\\../icons/maximize_window_black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_maximize_restore_window.setIcon(icon1)
        self.btn_maximize_restore_window.setObjectName("btn_maximize_restore_window")
        self.horizontalLayout_27.addWidget(self.btn_maximize_restore_window)
        self.horizontalLayout_25.addWidget(self.frame_23)
        self.frame_21 = QtWidgets.QFrame(self.frame_functional_butons)
        self.frame_21.setStyleSheet("border: none;")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.btn_close_window = QtWidgets.QPushButton(self.frame_21)
        self.btn_close_window.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_close_window.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_close_window.setStyleSheet("border-color: rgb(255, 0, 0);\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 0, 0);")
        self.btn_close_window.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("gui\\../icons/close_window_black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close_window.setIcon(icon2)
        self.btn_close_window.setIconSize(QtCore.QSize(20, 20))
        self.btn_close_window.setObjectName("btn_close_window")
        self.horizontalLayout_26.addWidget(self.btn_close_window)
        self.horizontalLayout_25.addWidget(self.frame_21)
        self.horizontalLayout_24.addWidget(self.frame_functional_butons, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.title_barWidget)
        self.contentwidget = QtWidgets.QWidget(self.centralwidget)
        self.contentwidget.setObjectName("contentwidget")
        self.content_main_layout = QtWidgets.QVBoxLayout(self.contentwidget)
        self.content_main_layout.setContentsMargins(0, 0, 0, 0)
        self.content_main_layout.setObjectName("content_main_layout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.contentwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_frame = QtWidgets.QWidget()
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_20 = QtWidgets.QFrame(self.main_frame)
        self.frame_20.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.frame_exclamation_bnt = QtWidgets.QFrame(self.frame_20)
        self.frame_exclamation_bnt.setMinimumSize(QtCore.QSize(50, 50))
        self.frame_exclamation_bnt.setMaximumSize(QtCore.QSize(50, 50))
        self.frame_exclamation_bnt.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_exclamation_bnt.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_exclamation_bnt.setObjectName("frame_exclamation_bnt")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_exclamation_bnt)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.btn_exclamation = QtWidgets.QPushButton(self.frame_exclamation_bnt)
        self.btn_exclamation.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_exclamation.setStyleSheet("QPushButton {\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"\n"
"    border-color: rgb(252, 135, 72);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border-style: inset;\n"
"}")
        self.btn_exclamation.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/acenu/.designer/icons/exclamation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_exclamation.setIcon(icon3)
        self.btn_exclamation.setIconSize(QtCore.QSize(30, 30))
        self.btn_exclamation.setObjectName("btn_exclamation")
        self.horizontalLayout_22.addWidget(self.btn_exclamation)
        self.horizontalLayout_21.addWidget(self.frame_exclamation_bnt)
        self.separator_frame = QtWidgets.QFrame(self.frame_20)
        self.separator_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.separator_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.separator_frame.setObjectName("separator_frame")
        self.horizontalLayout_21.addWidget(self.separator_frame)
        self.frame_setting_btn = QtWidgets.QFrame(self.frame_20)
        self.frame_setting_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.frame_setting_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.frame_setting_btn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_setting_btn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_setting_btn.setObjectName("frame_setting_btn")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_setting_btn)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btn_settings = QtWidgets.QPushButton(self.frame_setting_btn)
        self.btn_settings.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_settings.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_settings.setStyleSheet("QPushButton {\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"\n"
"    border-color: rgb(252, 135, 72);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border-style: inset;\n"
"}")
        self.btn_settings.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/Users/acenu/.designer/icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_settings.setIcon(icon4)
        self.btn_settings.setIconSize(QtCore.QSize(30, 30))
        self.btn_settings.setObjectName("btn_settings")
        self.horizontalLayout_9.addWidget(self.btn_settings)
        self.horizontalLayout_21.addWidget(self.frame_setting_btn)
        self.verticalLayout_5.addWidget(self.frame_20)
        self.frame_main = QtWidgets.QFrame(self.main_frame)
        self.frame_main.setMinimumSize(QtCore.QSize(600, 500))
        self.frame_main.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_main_btn = QtWidgets.QFrame(self.frame_main)
        self.frame_main_btn.setMinimumSize(QtCore.QSize(100, 100))
        self.frame_main_btn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main_btn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main_btn.setLineWidth(1)
        self.frame_main_btn.setObjectName("frame_main_btn")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_main_btn)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_start = QtWidgets.QPushButton(self.frame_main_btn)
        self.btn_start.setMinimumSize(QtCore.QSize(150, 60))
        self.btn_start.setStyleSheet("QPushButton {\n"
"    background-color: rgb(252, 110, 32);\n"
"    margin: 10px 0;\n"
"    border-radius: 15px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: rgb(252, 135, 72);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(254, 232, 208);\n"
"    background-color: rgb(50, 50, 50);\n"
"\n"
"}")
        self.btn_start.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.btn_start.setObjectName("btn_start")
        self.verticalLayout_4.addWidget(self.btn_start)
        self.btn_manage = QtWidgets.QPushButton(self.frame_main_btn)
        self.btn_manage.setMinimumSize(QtCore.QSize(150, 60))
        self.btn_manage.setStyleSheet("QPushButton {\n"
"    background-color: rgb(252, 110, 32);\n"
"    margin: 10px 0;\n"
"    border-radius: 15px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: rgb(252, 135, 72);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(254, 232, 208);\n"
"    background-color: rgb(50, 50, 50);\n"
"\n"
"}")
        self.btn_manage.setObjectName("btn_manage")
        self.verticalLayout_4.addWidget(self.btn_manage)
        self.verticalLayout_2.addWidget(self.frame_main_btn, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_5.addWidget(self.frame_main)
        self.frame_copyright = QtWidgets.QFrame(self.main_frame)
        self.frame_copyright.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_copyright.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_copyright.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_copyright.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_copyright.setObjectName("frame_copyright")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_copyright)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_copyright = QtWidgets.QLabel(self.frame_copyright)
        self.label_copyright.setObjectName("label_copyright")
        self.horizontalLayout.addWidget(self.label_copyright)
        self.verticalLayout_5.addWidget(self.frame_copyright)
        self.stackedWidget.addWidget(self.main_frame)
        self.frame_exclamation = QtWidgets.QWidget()
        self.frame_exclamation.setObjectName("frame_exclamation")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_exclamation)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.frame_settings_top_6 = QtWidgets.QFrame(self.frame_exclamation)
        self.frame_settings_top_6.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_settings_top_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_settings_top_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_settings_top_6.setObjectName("frame_settings_top_6")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_settings_top_6)
        self.verticalLayout_30.setContentsMargins(5, 5, 0, 5)
        self.verticalLayout_30.setSpacing(0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.btn_back_to_main_7 = QtWidgets.QPushButton(self.frame_settings_top_6)
        self.btn_back_to_main_7.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_back_to_main_7.setStyleSheet("QPushButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(135, 135, 135);\n"
"    border-style: inset;\n"
"}")
        self.btn_back_to_main_7.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:/Users/acenu/.designer/icons/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back_to_main_7.setIcon(icon5)
        self.btn_back_to_main_7.setIconSize(QtCore.QSize(35, 35))
        self.btn_back_to_main_7.setObjectName("btn_back_to_main_7")
        self.verticalLayout_30.addWidget(self.btn_back_to_main_7)
        self.verticalLayout_29.addWidget(self.frame_settings_top_6)
        self.label_7 = QtWidgets.QLabel(self.frame_exclamation)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_29.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.frame_exclamation)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_29.addWidget(self.label_6, 0, QtCore.Qt.AlignTop)
        self.frame_22 = QtWidgets.QFrame(self.frame_exclamation)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.btn_link_gmail = QtWidgets.QPushButton(self.frame_22)
        self.btn_link_gmail.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_link_gmail.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_link_gmail.setStyleSheet("QPushButton {\n"
"}\n"
"\n"
"QPushButton:pressed { \n"
"    padding: 5;\n"
"    border-style: none;\n"
"}")
        self.btn_link_gmail.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:/Users/acenu/.designer/icons/gmail.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_link_gmail.setIcon(icon6)
        self.btn_link_gmail.setIconSize(QtCore.QSize(45, 45))
        self.btn_link_gmail.setAutoDefault(False)
        self.btn_link_gmail.setDefault(False)
        self.btn_link_gmail.setFlat(True)
        self.btn_link_gmail.setObjectName("btn_link_gmail")
        self.horizontalLayout_23.addWidget(self.btn_link_gmail)
        self.btn_link_instagram = QtWidgets.QPushButton(self.frame_22)
        self.btn_link_instagram.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_link_instagram.setStyleSheet("QPushButton {\n"
"}\n"
"\n"
"QPushButton:pressed { \n"
"    padding: 5;\n"
"    border-style: none;\n"
"}")
        self.btn_link_instagram.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("C:/Users/acenu/.designer/icons/instagram.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_link_instagram.setIcon(icon7)
        self.btn_link_instagram.setIconSize(QtCore.QSize(45, 45))
        self.btn_link_instagram.setFlat(True)
        self.btn_link_instagram.setObjectName("btn_link_instagram")
        self.horizontalLayout_23.addWidget(self.btn_link_instagram)
        self.btn_link_telegram = QtWidgets.QPushButton(self.frame_22)
        self.btn_link_telegram.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_link_telegram.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_link_telegram.setStyleSheet("QPushButton {\n"
"}\n"
"\n"
"QPushButton:pressed { \n"
"    padding: 5;\n"
"    border-style: none;\n"
"}")
        self.btn_link_telegram.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("C:/Users/acenu/.designer/icons/telegram.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_link_telegram.setIcon(icon8)
        self.btn_link_telegram.setIconSize(QtCore.QSize(45, 45))
        self.btn_link_telegram.setFlat(True)
        self.btn_link_telegram.setObjectName("btn_link_telegram")
        self.horizontalLayout_23.addWidget(self.btn_link_telegram)
        self.btn_link_github = QtWidgets.QPushButton(self.frame_22)
        self.btn_link_github.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_link_github.setStyleSheet("QPushButton {\n"
"}\n"
"\n"
"QPushButton:pressed { \n"
"    padding: 5;\n"
"    border-style: none;\n"
"}")
        self.btn_link_github.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("C:/Users/acenu/.designer/icons/github.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_link_github.setIcon(icon9)
        self.btn_link_github.setIconSize(QtCore.QSize(45, 45))
        self.btn_link_github.setFlat(True)
        self.btn_link_github.setObjectName("btn_link_github")
        self.horizontalLayout_23.addWidget(self.btn_link_github)
        self.verticalLayout_29.addWidget(self.frame_22)
        self.stackedWidget.addWidget(self.frame_exclamation)
        self.start_frame = QtWidgets.QWidget()
        self.start_frame.setObjectName("start_frame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.start_frame)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_settings_top_3 = QtWidgets.QFrame(self.start_frame)
        self.frame_settings_top_3.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_settings_top_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_settings_top_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_settings_top_3.setObjectName("frame_settings_top_3")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_settings_top_3)
        self.horizontalLayout_16.setContentsMargins(5, 5, 0, 5)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.btn_back_to_main_3 = QtWidgets.QPushButton(self.frame_settings_top_3)
        self.btn_back_to_main_3.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_back_to_main_3.setStyleSheet("QPushButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(135, 135, 135);\n"
"    border-style: inset;\n"
"}")
        self.btn_back_to_main_3.setText("")
        self.btn_back_to_main_3.setIcon(icon5)
        self.btn_back_to_main_3.setIconSize(QtCore.QSize(35, 35))
        self.btn_back_to_main_3.setObjectName("btn_back_to_main_3")
        self.horizontalLayout_16.addWidget(self.btn_back_to_main_3, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_14.addWidget(self.frame_settings_top_3)
        self.frame_13 = QtWidgets.QFrame(self.start_frame)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_15.setContentsMargins(-1, -1, -1, 11)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_13)
        self.scrollArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollArea.setStyleSheet("border: none;")
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 732, 418))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_16.setContentsMargins(11, 11, -1, -1)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_15.addWidget(self.scrollArea)
        self.verticalLayout_14.addWidget(self.frame_13)
        self.stackedWidget.addWidget(self.start_frame)
        self.game_running_frame = QtWidgets.QWidget()
        self.game_running_frame.setStyleSheet("border: none;")
        self.game_running_frame.setObjectName("game_running_frame")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.game_running_frame)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(7)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.game_running_frame)
        self.scrollArea_2.setStyleSheet("QScrollBar:vertical {\n"
"    border: 2px solid gray;\n"
"    border-radius: 4px;\n"
"    background-color: rgb(0, 0, 0);\n"
"    width:10px;\n"
"    margin: 0px 0px 0px 0px;\n"
"    }\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: rgb(252, 110, 32);\n"
"    min-height: 0px;\n"
"    border: 0px solid rgb(252, 110, 32);\n"
"    border-radius: 4px;\n"
"    }\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    }\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0 px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"    }")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 778, 526))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_20.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frame_settings_top_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_settings_top_4.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_settings_top_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_settings_top_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_settings_top_4.setObjectName("frame_settings_top_4")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_settings_top_4)
        self.horizontalLayout_17.setContentsMargins(5, 5, 0, 5)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.btn_back_to_main_4 = QtWidgets.QPushButton(self.frame_settings_top_4)
        self.btn_back_to_main_4.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_back_to_main_4.setStyleSheet("QPushButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(135, 135, 135);\n"
"    border-style: inset;\n"
"}")
        self.btn_back_to_main_4.setText("")
        self.btn_back_to_main_4.setIcon(icon5)
        self.btn_back_to_main_4.setIconSize(QtCore.QSize(35, 35))
        self.btn_back_to_main_4.setObjectName("btn_back_to_main_4")
        self.horizontalLayout_17.addWidget(self.btn_back_to_main_4, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_20.addWidget(self.frame_settings_top_4)
        self.frame_question = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_question.setMinimumSize(QtCore.QSize(490, 300))
        self.frame_question.setStyleSheet("")
        self.frame_question.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_question.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_question.setObjectName("frame_question")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_question)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_question = QtWidgets.QLabel(self.frame_question)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_question.setFont(font)
        self.label_question.setMouseTracking(False)
        self.label_question.setStyleSheet("border: none;")
        self.label_question.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_question.setAlignment(QtCore.Qt.AlignCenter)
        self.label_question.setWordWrap(True)
        self.label_question.setObjectName("label_question")
        self.verticalLayout_17.addWidget(self.label_question)
        self.verticalLayout_20.addWidget(self.frame_question)
        self.frame_buttons = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_buttons.setStyleSheet("")
        self.frame_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons.setObjectName("frame_buttons")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_buttons)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_20.addWidget(self.frame_buttons)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_19.addWidget(self.scrollArea_2)
        self.stackedWidget.addWidget(self.game_running_frame)
        self.new_question_frame = QtWidgets.QWidget()
        self.new_question_frame.setObjectName("new_question_frame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.new_question_frame)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_10 = QtWidgets.QFrame(self.new_question_frame)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.frame_10)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_11.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_question = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_question.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_question.setObjectName("lineEdit_question")
        self.verticalLayout_11.addWidget(self.lineEdit_question)
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.listWidget_answers = QtWidgets.QListWidget(self.frame_11)
        self.listWidget_answers.setObjectName("listWidget_answers")
        self.horizontalLayout_15.addWidget(self.listWidget_answers)
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frame_12.setFont(font)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.btn_add_answer = QtWidgets.QPushButton(self.frame_12)
        self.btn_add_answer.setObjectName("btn_add_answer")
        self.verticalLayout_12.addWidget(self.btn_add_answer)
        self.btn_edit_answer = QtWidgets.QPushButton(self.frame_12)
        self.btn_edit_answer.setObjectName("btn_edit_answer")
        self.verticalLayout_12.addWidget(self.btn_edit_answer)
        self.btn_remove_answer = QtWidgets.QPushButton(self.frame_12)
        self.btn_remove_answer.setObjectName("btn_remove_answer")
        self.verticalLayout_12.addWidget(self.btn_remove_answer)
        self.horizontalLayout_15.addWidget(self.frame_12, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_11.addWidget(self.frame_11)
        self.verticalLayout_13.addWidget(self.frame_10)
        self.frame_9 = QtWidgets.QFrame(self.new_question_frame)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.btn_save_question = QtWidgets.QPushButton(self.frame_9)
        self.btn_save_question.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btn_save_question.setStyleSheet("QPushButton {\n"
"    background-color: green;\n"
"    border-style: outset;\n"
"    border-width: 3px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 86, 0);\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed { \n"
"    background-color: green;\n"
"    border-style: inset;\n"
"    border-width: 3px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 86, 0);\n"
"    min-width: 10em;\n"
"    padding: 6px; \n"
"}")
        self.btn_save_question.setObjectName("btn_save_question")
        self.horizontalLayout_14.addWidget(self.btn_save_question)
        self.btn_cancel_question = QtWidgets.QPushButton(self.frame_9)
        self.btn_cancel_question.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btn_cancel_question.setStyleSheet("QPushButton {\n"
"background-color: red;\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 10px;\n"
"border-color:rgb(158, 0, 0);\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed { \n"
"    background-color: red;\n"
"    border-style: inset;\n"
"    border-width: 3px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(158, 0, 0);\n"
"    min-width: 10em;\n"
"    padding: 6px; \n"
"}")
        self.btn_cancel_question.setObjectName("btn_cancel_question")
        self.horizontalLayout_14.addWidget(self.btn_cancel_question)
        self.verticalLayout_13.addWidget(self.frame_9)
        self.stackedWidget.addWidget(self.new_question_frame)
        self.new_answer_frame = QtWidgets.QWidget()
        self.new_answer_frame.setObjectName("new_answer_frame")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.new_answer_frame)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.frame_16 = QtWidgets.QFrame(self.new_answer_frame)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_3 = QtWidgets.QLabel(self.frame_16)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_24.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_answer = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_answer.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_answer.setObjectName("lineEdit_answer")
        self.verticalLayout_24.addWidget(self.lineEdit_answer)
        self.verticalLayout_26.addWidget(self.frame_16)
        self.frame_19 = QtWidgets.QFrame(self.new_answer_frame)
        self.frame_19.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_19.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.btn_save_answer = QtWidgets.QPushButton(self.frame_19)
        self.btn_save_answer.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btn_save_answer.setStyleSheet("QPushButton {\n"
"    background-color: green;\n"
"    border-style: outset;\n"
"    border-width: 3px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 86, 0);\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed { \n"
"    background-color: green;\n"
"    border-style: inset;\n"
"    border-width: 3px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 86, 0);\n"
"    min-width: 10em;\n"
"    padding: 6px; \n"
"}")
        self.btn_save_answer.setObjectName("btn_save_answer")
        self.horizontalLayout_19.addWidget(self.btn_save_answer)
        self.btn_cancel_answer = QtWidgets.QPushButton(self.frame_19)
        self.btn_cancel_answer.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btn_cancel_answer.setStyleSheet("QPushButton {\n"
"background-color: red;\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 10px;\n"
"border-color:rgb(158, 0, 0);\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed { \n"
"    background-color: red;\n"
"    border-style: inset;\n"
"    border-width: 3px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(158, 0, 0);\n"
"    min-width: 10em;\n"
"    padding: 6px; \n"
"}")
        self.btn_cancel_answer.setObjectName("btn_cancel_answer")
        self.horizontalLayout_19.addWidget(self.btn_cancel_answer)
        self.verticalLayout_26.addWidget(self.frame_19)
        self.stackedWidget.addWidget(self.new_answer_frame)
        self.new_quiz_frame = QtWidgets.QWidget()
        self.new_quiz_frame.setObjectName("new_quiz_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.new_quiz_frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_4 = QtWidgets.QFrame(self.new_quiz_frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_9.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_name_quiz = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_name_quiz.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_name_quiz.setObjectName("lineEdit_name_quiz")
        self.verticalLayout_9.addWidget(self.lineEdit_name_quiz)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.listWidget_questions = QtWidgets.QListWidget(self.frame_7)
        self.listWidget_questions.setObjectName("listWidget_questions")
        self.horizontalLayout_13.addWidget(self.listWidget_questions)
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.btn_add_question = QtWidgets.QPushButton(self.frame_8)
        self.btn_add_question.setObjectName("btn_add_question")
        self.verticalLayout_10.addWidget(self.btn_add_question)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_10.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_10.addWidget(self.pushButton_3)
        self.horizontalLayout_13.addWidget(self.frame_8)
        self.verticalLayout_9.addWidget(self.frame_7)
        self.verticalLayout_7.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.new_quiz_frame)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.btn_save_quiz = QtWidgets.QPushButton(self.frame_5)
        self.btn_save_quiz.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btn_save_quiz.setStyleSheet("QPushButton {\n"
"    background-color: green;\n"
"    border-style: outset;\n"
"    border-width: 3px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 86, 0);\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed { \n"
"    background-color: green;\n"
"    border-style: inset;\n"
"    border-width: 3px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 86, 0);\n"
"    min-width: 10em;\n"
"    padding: 6px; \n"
"}")
        self.btn_save_quiz.setObjectName("btn_save_quiz")
        self.horizontalLayout_12.addWidget(self.btn_save_quiz)
        self.btn_cancel_quiz = QtWidgets.QPushButton(self.frame_5)
        self.btn_cancel_quiz.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btn_cancel_quiz.setStyleSheet("QPushButton {\n"
"background-color: red;\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 10px;\n"
"border-color:rgb(158, 0, 0);\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed { \n"
"    background-color: red;\n"
"    border-style: inset;\n"
"    border-width: 3px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(158, 0, 0);\n"
"    min-width: 10em;\n"
"    padding: 6px; \n"
"}")
        self.btn_cancel_quiz.setObjectName("btn_cancel_quiz")
        self.horizontalLayout_12.addWidget(self.btn_cancel_quiz)
        self.verticalLayout_7.addWidget(self.frame_5)
        self.stackedWidget.addWidget(self.new_quiz_frame)
        self.manage_quiz_frame = QtWidgets.QWidget()
        self.manage_quiz_frame.setObjectName("manage_quiz_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.manage_quiz_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_settings_top_2 = QtWidgets.QFrame(self.manage_quiz_frame)
        self.frame_settings_top_2.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_settings_top_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_settings_top_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_settings_top_2.setObjectName("frame_settings_top_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_settings_top_2)
        self.horizontalLayout_10.setContentsMargins(5, 5, 0, 5)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btn_back_to_main_2 = QtWidgets.QPushButton(self.frame_settings_top_2)
        self.btn_back_to_main_2.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_back_to_main_2.setStyleSheet("QPushButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(135, 135, 135);\n"
"    border-style: inset;\n"
"}")
        self.btn_back_to_main_2.setText("")
        self.btn_back_to_main_2.setIcon(icon5)
        self.btn_back_to_main_2.setIconSize(QtCore.QSize(35, 35))
        self.btn_back_to_main_2.setObjectName("btn_back_to_main_2")
        self.horizontalLayout_10.addWidget(self.btn_back_to_main_2, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_3.addWidget(self.frame_settings_top_2)
        self.frame_6 = QtWidgets.QFrame(self.manage_quiz_frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.listWidget_quiz = QtWidgets.QListWidget(self.frame_6)
        self.listWidget_quiz.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.listWidget_quiz.setTextElideMode(QtCore.Qt.ElideRight)
        self.listWidget_quiz.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget_quiz.setObjectName("listWidget_quiz")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_quiz.addItem(item)
        self.horizontalLayout_11.addWidget(self.listWidget_quiz)
        self.frame_btn_manage_quiz = QtWidgets.QFrame(self.frame_6)
        self.frame_btn_manage_quiz.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_btn_manage_quiz.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_btn_manage_quiz.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btn_manage_quiz.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btn_manage_quiz.setObjectName("frame_btn_manage_quiz")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_btn_manage_quiz)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btn_new_quiz = QtWidgets.QPushButton(self.frame_btn_manage_quiz)
        self.btn_new_quiz.setObjectName("btn_new_quiz")
        self.verticalLayout_8.addWidget(self.btn_new_quiz)
        self.btn_edit_quiz = QtWidgets.QPushButton(self.frame_btn_manage_quiz)
        self.btn_edit_quiz.setObjectName("btn_edit_quiz")
        self.verticalLayout_8.addWidget(self.btn_edit_quiz)
        self.btn_remove_quiz = QtWidgets.QPushButton(self.frame_btn_manage_quiz)
        self.btn_remove_quiz.setObjectName("btn_remove_quiz")
        self.verticalLayout_8.addWidget(self.btn_remove_quiz)
        self.btn_import_quiz = QtWidgets.QPushButton(self.frame_btn_manage_quiz)
        self.btn_import_quiz.setObjectName("btn_import_quiz")
        self.verticalLayout_8.addWidget(self.btn_import_quiz)
        self.btn_export_quiz = QtWidgets.QPushButton(self.frame_btn_manage_quiz)
        self.btn_export_quiz.setObjectName("btn_export_quiz")
        self.verticalLayout_8.addWidget(self.btn_export_quiz)
        self.horizontalLayout_11.addWidget(self.frame_btn_manage_quiz)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.label_5 = QtWidgets.QLabel(self.manage_quiz_frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.stackedWidget.addWidget(self.manage_quiz_frame)
        self.rename_exist_file_frame = QtWidgets.QWidget()
        self.rename_exist_file_frame.setObjectName("rename_exist_file_frame")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.rename_exist_file_frame)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_4 = QtWidgets.QLabel(self.rename_exist_file_frame)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_27.addWidget(self.label_4)
        self.frame_17 = QtWidgets.QFrame(self.rename_exist_file_frame)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_quiz_name = QtWidgets.QLabel(self.frame_17)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_quiz_name.setFont(font)
        self.label_quiz_name.setStyleSheet("color: white;")
        self.label_quiz_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_quiz_name.setWordWrap(True)
        self.label_quiz_name.setObjectName("label_quiz_name")
        self.verticalLayout_25.addWidget(self.label_quiz_name)
        self.verticalLayout_27.addWidget(self.frame_17)
        self.lineEdit_rename_quiz = QtWidgets.QLineEdit(self.rename_exist_file_frame)
        self.lineEdit_rename_quiz.setAccessibleDescription("")
        self.lineEdit_rename_quiz.setStyleSheet("color: white;")
        self.lineEdit_rename_quiz.setText("")
        self.lineEdit_rename_quiz.setObjectName("lineEdit_rename_quiz")
        self.verticalLayout_27.addWidget(self.lineEdit_rename_quiz)
        self.frame_18 = QtWidgets.QFrame(self.rename_exist_file_frame)
        self.frame_18.setStyleSheet("color: white;")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.btn_replace = QtWidgets.QPushButton(self.frame_18)
        self.btn_replace.setStyleSheet("")
        self.btn_replace.setObjectName("btn_replace")
        self.horizontalLayout_18.addWidget(self.btn_replace)
        self.btn_rename = QtWidgets.QPushButton(self.frame_18)
        self.btn_rename.setObjectName("btn_rename")
        self.horizontalLayout_18.addWidget(self.btn_rename)
        self.btn_cancel_import_quiz = QtWidgets.QPushButton(self.frame_18)
        self.btn_cancel_import_quiz.setObjectName("btn_cancel_import_quiz")
        self.horizontalLayout_18.addWidget(self.btn_cancel_import_quiz)
        self.verticalLayout_27.addWidget(self.frame_18)
        self.stackedWidget.addWidget(self.rename_exist_file_frame)
        self.settings_frame = QtWidgets.QWidget()
        self.settings_frame.setObjectName("settings_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.settings_frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_settings_top = QtWidgets.QFrame(self.settings_frame)
        self.frame_settings_top.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_settings_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_settings_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_settings_top.setObjectName("frame_settings_top")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_settings_top)
        self.horizontalLayout_8.setContentsMargins(5, 5, 0, 5)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_back_to_main = QtWidgets.QPushButton(self.frame_settings_top)
        self.btn_back_to_main.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_back_to_main.setStyleSheet("QPushButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(135, 135, 135);\n"
"    border-style: inset;\n"
"}")
        self.btn_back_to_main.setText("")
        self.btn_back_to_main.setIcon(icon5)
        self.btn_back_to_main.setIconSize(QtCore.QSize(35, 35))
        self.btn_back_to_main.setObjectName("btn_back_to_main")
        self.horizontalLayout_8.addWidget(self.btn_back_to_main, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_6.addWidget(self.frame_settings_top)
        self.frame_language = QtWidgets.QFrame(self.settings_frame)
        self.frame_language.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_language.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_language.setObjectName("frame_language")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_language)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame = QtWidgets.QFrame(self.frame_language)
        self.frame.setMinimumSize(QtCore.QSize(100, 0))
        self.frame.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"\n"
"border-color: rgb(252, 135, 72);\n"
"color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_language = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_language.setFont(font)
        self.label_language.setStyleSheet("border: none;")
        self.label_language.setObjectName("label_language")
        self.horizontalLayout_2.addWidget(self.label_language, 0, QtCore.Qt.AlignVCenter)
        self.comboBox_language = QtWidgets.QComboBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_language.setFont(font)
        self.comboBox_language.setStyleSheet("")
        self.comboBox_language.setCurrentText("")
        self.comboBox_language.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_language.setObjectName("comboBox_language")
        self.horizontalLayout_2.addWidget(self.comboBox_language, 0, QtCore.Qt.AlignVCenter)
        self.horizontalLayout_7.addWidget(self.frame, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_6.addWidget(self.frame_language)
        self.frame_theme = QtWidgets.QFrame(self.settings_frame)
        self.frame_theme.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_theme.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_theme.setObjectName("frame_theme")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_theme)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.frame_theme)
        self.frame_2.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_2.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"\n"
"border-color: rgb(252, 135, 72);\n"
"color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_theme = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_theme.setFont(font)
        self.label_theme.setStyleSheet("border: none;")
        self.label_theme.setObjectName("label_theme")
        self.horizontalLayout_3.addWidget(self.label_theme, 0, QtCore.Qt.AlignVCenter)
        self.comboBox_theme = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_theme.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_theme.setFont(font)
        self.comboBox_theme.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_theme.setObjectName("comboBox_theme")
        self.comboBox_theme.addItem("")
        self.comboBox_theme.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_theme, 0, QtCore.Qt.AlignVCenter)
        self.horizontalLayout_4.addWidget(self.frame_2, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_6.addWidget(self.frame_theme)
        self.backgrownd_sound = QtWidgets.QFrame(self.settings_frame)
        self.backgrownd_sound.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.backgrownd_sound.setFrameShadow(QtWidgets.QFrame.Raised)
        self.backgrownd_sound.setObjectName("backgrownd_sound")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.backgrownd_sound)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_3 = QtWidgets.QFrame(self.backgrownd_sound)
        self.frame_3.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_3.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"\n"
"border-color: rgb(252, 135, 72);\n"
"color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_sound = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_sound.setFont(font)
        self.label_sound.setStyleSheet("border: none;")
        self.label_sound.setObjectName("label_sound")
        self.horizontalLayout_5.addWidget(self.label_sound, 0, QtCore.Qt.AlignVCenter)
        self.comboBox_sound = QtWidgets.QComboBox(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_sound.setFont(font)
        self.comboBox_sound.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_sound.setObjectName("comboBox_sound")
        self.comboBox_sound.addItem("")
        self.comboBox_sound.addItem("")
        self.comboBox_sound.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_sound, 0, QtCore.Qt.AlignVCenter)
        self.horizontalLayout_6.addWidget(self.frame_3, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_6.addWidget(self.backgrownd_sound)
        self.stackedWidget.addWidget(self.settings_frame)
        self.win_frame = QtWidgets.QWidget()
        self.win_frame.setObjectName("win_frame")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.win_frame)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frame_14 = QtWidgets.QFrame(self.win_frame)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_win = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_win.setFont(font)
        self.label_win.setAlignment(QtCore.Qt.AlignCenter)
        self.label_win.setObjectName("label_win")
        self.verticalLayout_22.addWidget(self.label_win)
        self.verticalLayout_21.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.win_frame)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.btn_back_to_main_5 = QtWidgets.QPushButton(self.frame_15)
        self.btn_back_to_main_5.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_back_to_main_5.setFont(font)
        self.btn_back_to_main_5.setObjectName("btn_back_to_main_5")
        self.verticalLayout_23.addWidget(self.btn_back_to_main_5)
        self.verticalLayout_21.addWidget(self.frame_15)
        self.stackedWidget.addWidget(self.win_frame)
        self.quiz_error_frame = QtWidgets.QWidget()
        self.quiz_error_frame.setObjectName("quiz_error_frame")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.quiz_error_frame)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.frame_settings_top_5 = QtWidgets.QFrame(self.quiz_error_frame)
        self.frame_settings_top_5.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_settings_top_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_settings_top_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_settings_top_5.setObjectName("frame_settings_top_5")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_settings_top_5)
        self.horizontalLayout_20.setContentsMargins(5, 5, 0, 5)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.btn_back_to_main_6 = QtWidgets.QPushButton(self.frame_settings_top_5)
        self.btn_back_to_main_6.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_back_to_main_6.setStyleSheet("QPushButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(135, 135, 135);\n"
"    border-style: inset;\n"
"}")
        self.btn_back_to_main_6.setText("")
        self.btn_back_to_main_6.setIcon(icon5)
        self.btn_back_to_main_6.setIconSize(QtCore.QSize(35, 35))
        self.btn_back_to_main_6.setObjectName("btn_back_to_main_6")
        self.horizontalLayout_20.addWidget(self.btn_back_to_main_6, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_28.addWidget(self.frame_settings_top_5)
        self.label_error_quiz = QtWidgets.QLabel(self.quiz_error_frame)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_error_quiz.setFont(font)
        self.label_error_quiz.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_error_quiz.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error_quiz.setObjectName("label_error_quiz")
        self.verticalLayout_28.addWidget(self.label_error_quiz)
        self.stackedWidget.addWidget(self.quiz_error_frame)
        self.content_main_layout.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.contentwidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "Quizz App"))
        self.btn_start.setText(_translate("MainWindow", "Start quiz"))
        self.btn_manage.setText(_translate("MainWindow", "Manage quiz"))
        self.label_copyright.setText(_translate("MainWindow", "Copyright"))
        self.label_7.setText(_translate("MainWindow", "Внимание!"))
        self.label_6.setText(_translate("MainWindow", "Данное приложение находится в разработке, и некоторые функции могут не работать, или работать некоректно. Если заметили баг или некоректную работу приложения,  пожалуйста свяжитесь со мной."))
        self.label_question.setText(_translate("MainWindow", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis velit, labore eligendi, praesentium doloremque placeat hic quis aspernatur optio facilis aut repellendus nihil nobis, eius voluptate officia recusandae itaque, reiciendis?"))
        self.label_2.setText(_translate("MainWindow", "Input the question"))
        self.btn_add_answer.setText(_translate("MainWindow", "add new answer"))
        self.btn_edit_answer.setText(_translate("MainWindow", "edit selected answer"))
        self.btn_remove_answer.setText(_translate("MainWindow", "remove  selected answer"))
        self.btn_save_question.setText(_translate("MainWindow", "Save"))
        self.btn_cancel_question.setText(_translate("MainWindow", "Cancel"))
        self.label_3.setText(_translate("MainWindow", "Input the answer"))
        self.btn_save_answer.setText(_translate("MainWindow", "Save"))
        self.btn_cancel_answer.setText(_translate("MainWindow", "Cancel"))
        self.label.setText(_translate("MainWindow", "enter the test title"))
        self.btn_add_question.setText(_translate("MainWindow", "add new question"))
        self.pushButton_2.setText(_translate("MainWindow", "edit selected question"))
        self.pushButton_3.setText(_translate("MainWindow", "remove selected question"))
        self.btn_save_quiz.setText(_translate("MainWindow", "Save"))
        self.btn_cancel_quiz.setText(_translate("MainWindow", "Cancel"))
        __sortingEnabled = self.listWidget_quiz.isSortingEnabled()
        self.listWidget_quiz.setSortingEnabled(False)
        item = self.listWidget_quiz.item(0)
        item.setText(_translate("MainWindow", "Example"))
        self.listWidget_quiz.setSortingEnabled(__sortingEnabled)
        self.btn_new_quiz.setText(_translate("MainWindow", "add new quiz"))
        self.btn_edit_quiz.setText(_translate("MainWindow", "edit selected quiz"))
        self.btn_remove_quiz.setText(_translate("MainWindow", "remove selected quiz"))
        self.btn_import_quiz.setText(_translate("MainWindow", "import the quiz"))
        self.btn_export_quiz.setText(_translate("MainWindow", "export the quiz"))
        self.label_5.setText(_translate("MainWindow", "Внимание! Некоторые функции из данного раздела могут работать некорректно!"))
        self.label_4.setText(_translate("MainWindow", "such file already exists!"))
        self.label_quiz_name.setText(_translate("MainWindow", "quiz name quiz name quiz name quiz name quiz name quiz name quiz name quiz name quiz name quiz name quiz name quiz name quiz name quiz name quiz name quiz name"))
        self.lineEdit_rename_quiz.setPlaceholderText(_translate("MainWindow", "write a new name for the quiz"))
        self.btn_replace.setText(_translate("MainWindow", "Replace file"))
        self.btn_rename.setText(_translate("MainWindow", "Rename file"))
        self.btn_cancel_import_quiz.setText(_translate("MainWindow", "Cancel"))
        self.label_language.setText(_translate("MainWindow", "Select language"))
        self.label_theme.setText(_translate("MainWindow", "Select theme"))
        self.comboBox_theme.setCurrentText(_translate("MainWindow", "Light"))
        self.comboBox_theme.setItemText(0, _translate("MainWindow", "Light"))
        self.comboBox_theme.setItemText(1, _translate("MainWindow", "Dark"))
        self.label_sound.setText(_translate("MainWindow", "Set background sound"))
        self.comboBox_sound.setItemText(0, _translate("MainWindow", "sound 1"))
        self.comboBox_sound.setItemText(1, _translate("MainWindow", "sound 2"))
        self.comboBox_sound.setItemText(2, _translate("MainWindow", "sound 3"))
        self.label_win.setText(_translate("MainWindow", "Congratulation, the quiz is over!"))
        self.btn_back_to_main_5.setText(_translate("MainWindow", "Back"))
        self.label_error_quiz.setText(_translate("MainWindow", "Sorry, unfortunately this quiz file is corrupted!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
